# ---------- Builder ----------
FROM python:3.11-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y gcc libpq-dev

COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps -r requirements.txt -w /wheels

# ---------- Runtime ----------
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=trackr.settings

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev curl

COPY --from=builder /wheels /wheels
RUN pip install --no-cache /wheels/*

COPY . .



EXPOSE 8000

HEALTHCHECK CMD python healthcheck.py || exit 1

CMD ["gunicorn", "trackr.wsgi:application", "--bind", "0.0.0.0:8000"]
