version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env.prod
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn trackr.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine